addons:
  # modules to install before running tests
  include:
    - contacts

  # modules to exclude from installation/testing
  exclude:
    - hw_proxy

  server_wide_modules:
    - web
    - ir_attachment_url
    - ir_config_parameter_multi_company
